'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.42.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="NfeRetRecepcaoSoap12", [Namespace]:="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao")>  _
Partial Public Class NfeRetRecepcao
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Private nfeRetRecepcaoOperationCompleted As System.Threading.SendOrPostCallback
    
    '''<remarks/>
    Public Sub New()
        MyBase.New
        Me.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12
        Me.Url = "https://homologacao.nfe.sefaz.rs.gov.br/ws/nferetrecepcao/nferetrecepcao.asmx"
    End Sub
    
    '''<remarks/>
    Public Event nfeRetRecepcaoCompleted As nfeRetRecepcaoCompletedEventHandler
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao/nfeRetRecepcao", RequestNamespace:="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao", ResponseNamespace:="http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetRecepcao", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function nfeRetRecepcao(ByVal nfeCabecMsg As String, ByVal nfeDadosMsg As String) As String
        Dim results() As Object = Me.Invoke("nfeRetRecepcao", New Object() {nfeCabecMsg, nfeDadosMsg})
        Return CType(results(0),String)
    End Function
    
    '''<remarks/>
    Public Function BeginnfeRetRecepcao(ByVal nfeCabecMsg As String, ByVal nfeDadosMsg As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("nfeRetRecepcao", New Object() {nfeCabecMsg, nfeDadosMsg}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndnfeRetRecepcao(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),String)
    End Function
    
    '''<remarks/>
    Public Overloads Sub nfeRetRecepcaoAsync(ByVal nfeCabecMsg As String, ByVal nfeDadosMsg As String)
        Me.nfeRetRecepcaoAsync(nfeCabecMsg, nfeDadosMsg, Nothing)
    End Sub
    
    '''<remarks/>
    Public Overloads Sub nfeRetRecepcaoAsync(ByVal nfeCabecMsg As String, ByVal nfeDadosMsg As String, ByVal userState As Object)
        If (Me.nfeRetRecepcaoOperationCompleted Is Nothing) Then
            Me.nfeRetRecepcaoOperationCompleted = AddressOf Me.OnnfeRetRecepcaoOperationCompleted
        End If
        Me.InvokeAsync("nfeRetRecepcao", New Object() {nfeCabecMsg, nfeDadosMsg}, Me.nfeRetRecepcaoOperationCompleted, userState)
    End Sub
    
    Private Sub OnnfeRetRecepcaoOperationCompleted(ByVal arg As Object)
        If (Not (Me.nfeRetRecepcaoCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent nfeRetRecepcaoCompleted(Me, New nfeRetRecepcaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub
    
    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
Public Delegate Sub nfeRetRecepcaoCompletedEventHandler(ByVal sender As Object, ByVal e As nfeRetRecepcaoCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class nfeRetRecepcaoCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As String
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),String)
        End Get
    End Property
End Class
